<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Employee 1
        DB::table('employees')->insert([
            'title' => 'Mr',
            'full_name' => 'Tendai Moyo',
            'national_id' => '63-214783F47',
            'date_of_birth' => '1985-06-12',
            'gender' => 'male',
            'marital_status' => 'married',
            'dependents' => 3,
            'physical_address' => '24 Greystone Park, Harare',
            'accommodation_type' => 'owned',
            'postal_address' => 'P.O. Box CY 1234, Causeway, Harare',
            'cell_phone' => '263772456789',
            'email' => 'tendai.moyo@example.com',
            'next_of_kin' => 'Grace Moyo',
            'next_of_kin_address' => '24 Greystone Park, Harare',
            'next_of_kin_cell' => '263773456123',
            'branch_id' => 1,
            'salary_gross' => 2500.00,
            'salary_net' => 2100.00,
            'department' => 'Finance',
            'position' => 'Finance Manager',
            'hire_date' => '2018-01-15',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 2
        DB::table('employees')->insert([
            'title' => 'Mrs',
            'full_name' => 'Nyasha Chikwanda',
            'national_id' => '08-765432A21',
            'date_of_birth' => '1990-09-23',
            'gender' => 'female',
            'marital_status' => 'married',
            'dependents' => 2,
            'physical_address' => '45 Avondale, Harare',
            'accommodation_type' => 'rented',
            'postal_address' => 'P.O. Box 8765, Avondale, Harare',
            'cell_phone' => '263712345678',
            'email' => 'nyasha.chikwanda@example.com',
            'next_of_kin' => 'Tawanda Chikwanda',
            'next_of_kin_address' => '45 Avondale, Harare',
            'next_of_kin_cell' => '263713456789',
            'branch_id' => 2,
            'salary_gross' => 1800.00,
            'salary_net' => 1540.00,
            'department' => 'HR',
            'position' => 'HR Manager',
            'hire_date' => '2019-03-21',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 3
        DB::table('employees')->insert([
            'title' => 'Mr',
            'full_name' => 'Tatenda Mupfumi',
            'national_id' => '45-892367K63',
            'date_of_birth' => '1988-11-05',
            'gender' => 'male',
            'marital_status' => 'single',
            'dependents' => 0,
            'physical_address' => '123 Nketa, Bulawayo',
            'accommodation_type' => 'family',
            'postal_address' => 'P.O. Box 456, Bulawayo',
            'cell_phone' => '263772123987',
            'email' => 'tatenda.mupfumi@example.com',
            'next_of_kin' => 'Sharon Mupfumi',
            'next_of_kin_address' => '67 Famona, Bulawayo',
            'next_of_kin_cell' => '263773987654',
            'branch_id' => 3,
            'salary_gross' => 1950.00,
            'salary_net' => 1670.00,
            'department' => 'ICT',
            'position' => 'ICT Support Specialist',
            'hire_date' => '2020-07-14',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 4
        DB::table('employees')->insert([
            'title' => 'Ms',
            'full_name' => 'Chipo Mutasa',
            'national_id' => '75-234185P11',
            'date_of_birth' => '1992-04-17',
            'gender' => 'female',
            'marital_status' => 'single',
            'dependents' => 1,
            'physical_address' => '78 Mkoba, Gweru',
            'accommodation_type' => 'rented',
            'postal_address' => 'P.O. Box 789, Gweru',
            'cell_phone' => '263712987456',
            'email' => 'chipo.mutasa@example.com',
            'next_of_kin' => 'Thomas Mutasa',
            'next_of_kin_address' => '34 Senga, Gweru',
            'next_of_kin_cell' => '263713789456',
            'branch_id' => 4,
            'salary_gross' => 1600.00,
            'salary_net' => 1380.00,
            'department' => 'Marketing',
            'position' => 'Customer Service Representative',
            'hire_date' => '2021-02-09',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 5
        DB::table('employees')->insert([
            'title' => 'Mr',
            'full_name' => 'Farai Dube',
            'national_id' => '15-678234J42',
            'date_of_birth' => '1983-08-21',
            'gender' => 'male',
            'marital_status' => 'divorced',
            'dependents' => 2,
            'physical_address' => '56 Dangamvura, Mutare',
            'accommodation_type' => 'owned',
            'postal_address' => 'P.O. Box 234, Mutare',
            'cell_phone' => '263772345876',
            'email' => 'farai.dube@example.com',
            'next_of_kin' => 'Rumbidzai Dube',
            'next_of_kin_address' => '12 Chikanga, Mutare',
            'next_of_kin_cell' => '263712567432',
            'branch_id' => 5,
            'salary_gross' => 2100.00,
            'salary_net' => 1790.00,
            'department' => 'Operations',
            'position' => 'Branch Manager',
            'hire_date' => '2017-11-03',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 6
        DB::table('employees')->insert([
            'title' => 'Mrs',
            'full_name' => 'Rudo Chikonamombe',
            'national_id' => '83-456123T78',
            'date_of_birth' => '1989-03-14',
            'gender' => 'female',
            'marital_status' => 'married',
            'dependents' => 3,
            'physical_address' => '23 Rujeko, Masvingo',
            'accommodation_type' => 'rented',
            'postal_address' => 'P.O. Box 567, Masvingo',
            'cell_phone' => '263713678912',
            'email' => 'rudo.chikonamombe@example.com',
            'next_of_kin' => 'Tapiwa Chikonamombe',
            'next_of_kin_address' => '23 Rujeko, Masvingo',
            'next_of_kin_cell' => '263772912345',
            'branch_id' => 6,
            'salary_gross' => 1850.00,
            'salary_net' => 1580.00,
            'department' => 'Retail',
            'position' => 'Retail Manager',
            'hire_date' => '2018-09-18',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 7
        DB::table('employees')->insert([
            'title' => 'Mr',
            'full_name' => 'Kudakwashe Ncube',
            'national_id' => '54-123987H32',
            'date_of_birth' => '1991-12-07',
            'gender' => 'male',
            'marital_status' => 'single',
            'dependents' => 0,
            'physical_address' => '89 Mt Pleasant, Harare',
            'accommodation_type' => 'family',
            'postal_address' => 'P.O. Box 9012, Harare',
            'cell_phone' => '263772876543',
            'email' => 'kuda.ncube@example.com',
            'next_of_kin' => 'Simba Ncube',
            'next_of_kin_address' => '45 Borrowdale, Harare',
            'next_of_kin_cell' => '263712765432',
            'branch_id' => 1,
            'salary_gross' => 2250.00,
            'salary_net' => 1920.00,
            'department' => 'Legal',
            'position' => 'Legal Advisor',
            'hire_date' => '2019-06-24',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 8
        DB::table('employees')->insert([
            'title' => 'Ms',
            'full_name' => 'Tsitsi Zimunya',
            'national_id' => '27-908765R54',
            'date_of_birth' => '1994-05-29',
            'gender' => 'female',
            'marital_status' => 'single',
            'dependents' => 1,
            'physical_address' => '34 Mbare, Harare',
            'accommodation_type' => 'rented',
            'postal_address' => 'P.O. Box 3456, Harare',
            'cell_phone' => '263713234567',
            'email' => 'tsitsi.zimunya@example.com',
            'next_of_kin' => 'Tinashe Zimunya',
            'next_of_kin_address' => '56 Highfield, Harare',
            'next_of_kin_cell' => '263772543210',
            'branch_id' => 2,
            'salary_gross' => 1400.00,
            'salary_net' => 1220.00,
            'department' => 'Marketing',
            'position' => 'Customer Service Officer',
            'hire_date' => '2022-01-10',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 9
        DB::table('employees')->insert([
            'title' => 'Mr',
            'full_name' => 'Tinotenda Gumbo',
            'national_id' => '38-567890D67',
            'date_of_birth' => '1987-07-03',
            'gender' => 'male',
            'marital_status' => 'married',
            'dependents' => 4,
            'physical_address' => '67 Emakhandeni, Bulawayo',
            'accommodation_type' => 'owned',
            'postal_address' => 'P.O. Box 678, Bulawayo',
            'cell_phone' => '263772098765',
            'email' => 'tino.gumbo@example.com',
            'next_of_kin' => 'Melody Gumbo',
            'next_of_kin_address' => '67 Emakhandeni, Bulawayo',
            'next_of_kin_cell' => '263713876543',
            'branch_id' => 3,
            'salary_gross' => 1750.00,
            'salary_net' => 1500.00,
            'department' => 'Marketing',
            'position' => 'Marketing Officer',
            'hire_date' => '2020-03-15',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Employee 10
        DB::table('employees')->insert([
            'title' => 'Dr',
            'full_name' => 'Vimbai Mushaninga',
            'national_id' => '92-345678L90',
            'date_of_birth' => '1980-01-18',
            'gender' => 'female',
            'marital_status' => 'widowed',
            'dependents' => 2,
            'physical_address' => '12 Ascot, Gweru',
            'accommodation_type' => 'owned',
            'postal_address' => 'P.O. Box 1234, Gweru',
            'cell_phone' => '263713456789',
            'email' => 'vimbai.mushaninga@example.com',
            'next_of_kin' => 'Panashe Mushaninga',
            'next_of_kin_address' => '45 Mkoba, Gweru',
            'next_of_kin_cell' => '263772345678',
            'branch_id' => 4,
            'salary_gross' => 2800.00,
            'salary_net' => 2350.00,
            'department' => 'Executive',
            'position' => 'Regional Director',
            'hire_date' => '2016-08-05',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
    }
}